# Generated by Django 5.0.1 on 2024-04-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authenticationcode_remove_user_is_authorized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Инвайт код'),
        ),
    ]
