# Generated by Django 5.0.1 on 2024-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_invite_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticationcode',
            options={'verbose_name': 'Код', 'verbose_name_plural': 'Коды'},
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='', max_length=20, verbose_name='Реферальный код'),
        ),
    ]
