# Generated by Django 5.0.1 on 2024-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_authenticationcode_options_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='', max_length=6, unique=True, verbose_name='Инвайт код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default='', max_length=6, verbose_name='Реферальный код'),
        ),
    ]
