# Generated by Django 5.0.1 on 2024-04-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_invite_code_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Реферальный код'),
        ),
    ]
